### ISSUE TITLE
请问一下  为啥有些会提示普通评价失败的?

### ISSUE THREAD

**Issue by cmazfuture** [2079898548/jd_lzsnmb#9]
![22222](https://user-images.githubusercontent.com/71751136/140647311-306bde53-9ccc-4b75-9afc-02b5a2c4c0dd.png)
请问一下  为啥有些会提示普通评价失败的?

**Comment by Ocyss** [comment]
技术有限。手机版问题很多，主要现在也没要评价的订单测试。。。。
仓库有网页版的，超完整 保证全评价完，可以试试。
手机版等下次再试。












lzsnmb
***@***.***


---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年11月7日(周日) 晚上9:37
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [qiu-lzsnmb/jd_lzsnmb] 请问一下  为啥有些会提示普通评价失败的? (Issue #9)




 

 请问一下  为啥有些会提示普通评价失败的?
 
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by cmazfuture** [comment]
![QQ图片20211107223027](https://user-images.githubusercontent.com/71751136/140649278-7e4a744a-850a-4487-9a56-e228ac9bffb7.png)
电脑端的  请问CK文件填在哪里? ,第一个箭头我填进去运行有问题,第二个箭头,我把CK删了,把真正的CK填进去也是报错

**Comment by Ocyss** [comment]
只用填上面的ck，ck要用网页版的。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年11月7日(周日) 晚上10:31
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [qiu-lzsnmb/jd_lzsnmb] 请问一下  为啥有些会提示普通评价失败的? (Issue #9)




 

 电脑端的  请问CK文件填在哪里? ,第一个箭头我填进去运行有问题,第二个箭头,我把CK删了,把真正的CK填进去也是报错
 
—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
